export type BusinessSelector = {
  testId: string
  priority: 'P0' | 'P1' | 'P2'
  owner: 'auth' | 'product' | 'production' | 'listing' | 'export' | 'download' | 'inventory'
  sourcePath: string
  purpose: string
  qaIds: string[]
}

export const BUSINESS_SELECTORS: Record<string, BusinessSelector> = {
  authLoginForm: {
    testId: 'auth-login-form',
    priority: 'P0',
    owner: 'auth',
    sourcePath: 'src/pages/auth/LoginPage.tsx',
    purpose: 'Login form boundary for authenticated business workspaces.',
    qaIds: ['ecom-auth-protected-route'],
  },
  authLoginSubmit: {
    testId: 'auth-login-submit',
    priority: 'P0',
    owner: 'auth',
    sourcePath: 'src/pages/auth/LoginPage.tsx',
    purpose: 'Login submit CTA.',
    qaIds: ['ecom-auth-protected-route'],
  },
  productListPage: {
    testId: 'product-list-page',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductListPage.tsx',
    purpose: 'Product Center route identity.',
    qaIds: ['ecom-product-create-list-detail', 'ecom-product-scoped-visual-entry'],
  },
  productCreateOpen: {
    testId: 'product-create-open',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductListPage.tsx',
    purpose: 'Open create SKU modal.',
    qaIds: ['ecom-product-create-list-detail'],
  },
  productCreateSkuCode: {
    testId: 'product-create-sku-code',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductListPage.tsx',
    purpose: 'Create SKU form code field for the create -> list -> detail journey.',
    qaIds: ['ecom-product-create-list-detail'],
  },
  productCreateTitle: {
    testId: 'product-create-title',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductListPage.tsx',
    purpose: 'Create SKU form title field for the create -> list -> detail journey.',
    qaIds: ['ecom-product-create-list-detail'],
  },
  productCreateSubmit: {
    testId: 'product-create-submit',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductListPage.tsx',
    purpose: 'Submit create SKU mutation.',
    qaIds: ['ecom-product-create-list-detail'],
  },
  productRow: {
    testId: 'product-row',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductListPage.tsx',
    purpose: 'Product list row with data-product-id and data-sku-code.',
    qaIds: ['ecom-product-create-list-detail', 'ecom-product-scoped-visual-entry'],
  },
  productRowOpenDetail: {
    testId: 'product-row-open-detail',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductListPage.tsx',
    purpose: 'Open product detail from list.',
    qaIds: ['ecom-product-create-list-detail'],
  },
  productDetailPage: {
    testId: 'product-detail-page',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductDetailPage.tsx',
    purpose: 'Product detail page identity with product and SKU data attributes.',
    qaIds: ['ecom-product-create-list-detail', 'ecom-product-edit-persistence', 'ecom-listing-export-download'],
  },
  productVisualEntry: {
    testId: 'product-visual-entry',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductListPage.tsx',
    purpose: 'Product-scoped visual production entry CTA.',
    qaIds: ['ecom-product-scoped-visual-entry'],
  },
  productionPrepPage: {
    testId: 'production-prep-page',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/PrepHubPage.tsx',
    purpose: 'Production Prep route identity.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionSourceUploadSku: {
    testId: 'production-source-upload-sku',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/PrepHubPage.tsx',
    purpose: 'SKU source upload boundary.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionSourceUploadReference: {
    testId: 'production-source-upload-reference',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/PrepHubPage.tsx',
    purpose: 'Reference source upload boundary.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionParseStart: {
    testId: 'production-parse-start',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/PrepHubPage.tsx',
    purpose: 'Start image understanding parse.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionChoiceCard: {
    testId: 'production-choice-card',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/components/production/ProductionWorkflowComponents.tsx',
    purpose: 'Fixed Prep choice card.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionChoiceSubmit: {
    testId: 'production-choice-submit',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/components/production/ProductionWorkflowComponents.tsx',
    purpose: 'Fixed Prep choice option.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionNextSandbox: {
    testId: 'production-next-sandbox',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/PrepHubPage.tsx',
    purpose: 'Prep to Sandbox transition CTA.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionSandboxPage: {
    testId: 'production-sandbox-page',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/SandboxPage.tsx',
    purpose: 'Production Sandbox route identity.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionPromptCompose: {
    testId: 'production-prompt-compose',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/SandboxPage.tsx',
    purpose: 'Generate/refresh user-facing image plan.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionGenerationStart: {
    testId: 'production-generation-start',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/SandboxPage.tsx',
    purpose: 'Start generation only when ready.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionWorkshopPage: {
    testId: 'production-workshop-page',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/WorkshopPage.tsx',
    purpose: 'Workshop route identity.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  productionVersionCard: {
    testId: 'production-version-card',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/components/production/ProductionWorkflowComponents.tsx',
    purpose: 'Generation version lineage card.',
    qaIds: ['ecom-production-prep-sandbox-workshop'],
  },
  listingCreateOpen: {
    testId: 'listing-create-open',
    priority: 'P0',
    owner: 'listing',
    sourcePath: 'src/pages/product/ProductDetailPage.tsx',
    purpose: 'Open listing version create/edit dialog from the SKU detail header.',
    qaIds: ['ecom-listing-export-download'],
  },
  listingCreateOpenSecondary: {
    testId: 'listing-create-open-secondary',
    priority: 'P0',
    owner: 'listing',
    sourcePath: 'src/pages/product/ProductDetailPage.tsx',
    purpose: 'Open listing version create/edit dialog from the listing card.',
    qaIds: ['ecom-listing-export-download'],
  },
  listingCreateSubmit: {
    testId: 'listing-create-submit',
    priority: 'P0',
    owner: 'listing',
    sourcePath: 'src/pages/product/ProductDetailPage.tsx',
    purpose: 'Create or save listing version mutation.',
    qaIds: ['ecom-listing-export-download'],
  },
  listingAdoptSubmit: {
    testId: 'listing-adopt-submit',
    priority: 'P0',
    owner: 'listing',
    sourcePath: 'src/pages/product/ProductDetailPage.tsx',
    purpose: 'Adopt listing version mutation when row actions are present.',
    qaIds: ['ecom-listing-export-download'],
  },
  exportCreateOpen: {
    testId: 'export-create-open',
    priority: 'P0',
    owner: 'export',
    sourcePath: 'src/pages/product/ProductDetailPage.tsx',
    purpose: 'Open export package/task dialog from SKU detail.',
    qaIds: ['ecom-listing-export-download'],
  },
  exportCreateSubmit: {
    testId: 'export-create-submit',
    priority: 'P0',
    owner: 'export',
    sourcePath: 'src/pages/product/ProductDetailPage.tsx',
    purpose: 'Create export package/task mutation.',
    qaIds: ['ecom-listing-export-download'],
  },
  downloadRecordCard: {
    testId: 'download-record-card',
    priority: 'P0',
    owner: 'download',
    sourcePath: 'src/pages/account/AccountDownloadsPage.tsx',
    purpose: 'Download record card with product/export context.',
    qaIds: ['ecom-listing-export-download'],
  },
  downloadRecordDownload: {
    testId: 'download-record-download',
    priority: 'P0',
    owner: 'download',
    sourcePath: 'src/pages/account/AccountDownloadsPage.tsx',
    purpose: 'Authenticated download action.',
    qaIds: ['ecom-listing-export-download', 'ecom-downloads-auth-content'],
  },
  productDetailTitleInput: {
    testId: 'product-detail-title-input',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductDetailPage.tsx',
    purpose: 'Editable title field on product detail for edit persistence journey.',
    qaIds: ['ecom-product-edit-persistence'],
  },
  productDetailSaveStatus: {
    testId: 'product-detail-save-status',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/ProductDetailPage.tsx',
    purpose: 'Save status indicator after PATCH.',
    qaIds: ['ecom-product-edit-persistence'],
  },
  visualToolsPage: {
    testId: 'visual-tools-page',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/ProductVisualToolsPage.tsx',
    purpose: 'Visual Tools workspace identity.',
    qaIds: ['ecom-visual-tools-entry'],
  },
  productionVersionCard: {
    testId: 'production-version-card',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/components/production/ProductionWorkflowComponents.tsx',
    purpose: 'Generation version lineage card.',
    qaIds: ['ecom-production-prep-sandbox-workshop', 'ecom-workshop-generation-result'],
  },
  productionResultAsset: {
    testId: 'production-result-card',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/components/production/ProductionWorkflowComponents.tsx',
    purpose: 'Result asset thumbnail in Workshop.',
    qaIds: ['ecom-workshop-generation-result'],
  },
  // ─── Product Detail AI Pipeline ──────────────────────────────
  productDetailHeader: {
    testId: 'product-detail-header',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'Product detail header with SKU and metrics.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  productDetailHealthBadge: {
    testId: 'product-detail-health-badge',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'Health badge showing pipeline readiness.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  productDetailPrimaryCta: {
    testId: 'product-detail-primary-cta',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'Primary CTA for next pipeline action.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  productAIPipeline: {
    testId: 'product-ai-pipeline',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'AI Pipeline section root.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  productParsedInfoPanel: {
    testId: 'product-parsed-info-panel',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'Parsed info panel.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  productPromptVersionsPanel: {
    testId: 'product-prompt-versions-panel',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'Prompt versions panel.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  productPromptGenerateButton: {
    testId: 'product-prompt-generate-button',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'Generate prompt button.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  pipelineNextActionCard: {
    testId: 'pipeline-next-action-card',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'Next action card with blocker list.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  pipelineNextActionButton: {
    testId: 'pipeline-next-action-button',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'Next action button.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  pipelineBlockersList: {
    testId: 'pipeline-blockers-list',
    priority: 'P0',
    owner: 'product',
    sourcePath: 'src/pages/product/components/ProductAIPipelinePanel.tsx',
    purpose: 'Blockers list when pipeline is blocked.',
    qaIds: ['ecom-product-detail-pipeline'],
  },
  // ─── Workshop ────────────────────────────────────────────────
  productionWorkshopFinalize: {
    testId: 'production-workshop-finalize',
    priority: 'P0',
    owner: 'production',
    sourcePath: 'src/pages/production/WorkshopPage.tsx',
    purpose: 'Workshop finalize/backflow CTA.',
    qaIds: ['ecom-production-workshop-finalize'],
  },
  // ─── Inventory ───────────────────────────────────────────────
  inventoryDashboardPage: {
    testId: 'inventory-dashboard-page',
    priority: 'P0',
    owner: 'inventory',
    sourcePath: 'src/pages/inventory/InventoryDashboardPage.tsx',
    purpose: 'Inventory dashboard route identity.',
    qaIds: ['ecom-inventory-routes'],
  },
  inventoryDashboardTitle: {
    testId: 'inventory-dashboard-title',
    priority: 'P0',
    owner: 'inventory',
    sourcePath: 'src/pages/inventory/InventoryDashboardPage.tsx',
    purpose: 'Inventory dashboard title.',
    qaIds: ['ecom-inventory-routes'],
  },
  inventoryStatsPanel: {
    testId: 'inventory-stats-panel',
    priority: 'P0',
    owner: 'inventory',
    sourcePath: 'src/pages/inventory/InventoryDashboardPage.tsx',
    purpose: 'Inventory stats cards panel.',
    qaIds: ['ecom-inventory-routes'],
  },
  inventoryProductTable: {
    testId: 'inventory-product-table',
    priority: 'P0',
    owner: 'inventory',
    sourcePath: 'src/pages/inventory/InventoryDashboardPage.tsx',
    purpose: 'Inventory product table.',
    qaIds: ['ecom-inventory-routes'],
  },
  inventoryTableToolbar: {
    testId: 'inventory-table-toolbar',
    priority: 'P0',
    owner: 'inventory',
    sourcePath: 'src/pages/inventory/InventoryDashboardPage.tsx',
    purpose: 'Inventory table toolbar with filters.',
    qaIds: ['ecom-inventory-routes'],
  },
  inventoryProductRow: {
    testId: 'inventory-product-row',
    priority: 'P0',
    owner: 'inventory',
    sourcePath: 'src/pages/inventory/InventoryDashboardPage.tsx',
    purpose: 'Inventory product row.',
    qaIds: ['ecom-inventory-routes'],
  },
}

export const selector = (key: keyof typeof BUSINESS_SELECTORS) => `[data-testid="${BUSINESS_SELECTORS[key].testId}"]`

export const INTERNAL_TERM_PATTERNS = [
  /prompt_plan/i,
  /prompt_id/i,
  /runtime/i,
  /provider/i,
  /backend/i,
  /contract[-_ ]?needed/i,
  /\bblocker\b/i,
  /result asset/i,
  /callback/i,
  /stage-view/i,
  /deconstruction_elements/i,
  /\[object Object\]/i,
]
