import { Input } from './Input'

export default {
  title: 'Ecommerce UI/Input',
  component: Input,
}

export function States() {
  return (
    <div className="max-w-md space-y-4 bg-[var(--ecom-bg)] p-6">
      <Input id="sku" name="sku" label="SKU" placeholder="SKU-001" helperText="Use product SKU code." />
      <Input id="search" name="search" label="Search" placeholder="Search products…" inputSize="lg" />
      <Input id="error" name="error" label="Product title" defaultValue="" error="Product title is required." />
      <Input id="disabled" name="disabled" label="Read only" value="Generated by system" disabled readOnly />
    </div>
  )
}
